import type { Metadata } from "next";
import { dosis } from "./ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "~Max Wynn~",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${dosis.className} antialiased`}>{children}</body>
    </html>
  );
}
